#!/usr/bin/env node
/**
 * Manual entry point for `pnpm dev`, `pnpm build`, and `pnpm live`.
 * Validates that tarballs exist (error if not, prompt to run pnpm prep),
 * runs `npm install` lazily on first use, then runs the requested docmd
 * command in-place. Errors with a clear message instead of failing with
 * a cryptic "module not found" on a fresh clone that hasn't run prep yet.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tarsDir = path.join(__dirname, 'local-tars');
const nodeModules = path.join(__dirname, 'node_modules');

const command = process.argv[2];
if (!['dev', 'build', 'live'].includes(command)) {
  console.error(`Usage: node dev.js <dev|build|live>`);
  process.exit(1);
}

function fail(msg) {
  console.error(`\n  \x1b[31m✗\x1b[0m ${msg}\n`);
  process.exit(1);
}

// Tarballs must be present. Generated by pnpm prep, never on demand here.
if (!existsSync(tarsDir)) {
  fail('local-tars/ not found. Run `pnpm prep` first to build the monorepo and generate tarballs.');
}
const tars = existsSync(tarsDir) ? readdirSync(tarsDir).filter((f) => f.endsWith('.tgz')) : [];
if (tars.length === 0) {
  fail('local-tars/ is empty. Run `pnpm prep` first to generate tarballs.');
}

// node_modules — install lazily on first dev/build/live run so `pnpm prep`
// does not pollute with a full install.
const env = { ...process.env };
delete env.npm_config_npm_globalconfig;
delete env.npm_config_verify_deps_before_run;
delete env.npm_config__jsr_registry;

if (!existsSync(nodeModules)) {
  console.log(`\n  \x1b[36m→\x1b[0m installing beta-test dependencies (one-time)…\n`);
  const r = spawnSync('npm', ['install', '--no-audit', '--no-fund', '--include=optional', '--foreground-scripts'], {
    cwd: __dirname,
    stdio: 'inherit',
    env,
  });
  if (r.status !== 0) fail(`npm install failed (exit ${r.status})`);
}

const cmdArgs = command === 'live' ? ['docmd-live'] : ['docmd', command];
const r = spawnSync('npx', cmdArgs, { cwd: __dirname, stdio: 'inherit', env });
process.exit(r.status ?? 0);
